[[2023.01.1]]
lang = "Rust"
name = "Naive"
desc = "A somewhat simple, iterator-based solution"

path = "solutions/Rust/2023/d1p1_naive"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d1p1_naive"
clean = "cargo clean"

[[2023.01.1]]
lang = "Rust"
name = "Iterator"
desc = "An iterator-based solution"

path = "solutions/Rust/2023/d1p1_onepass"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d1p1_onepass"
clean = "cargo clean"

[[2023.01.1]]
lang = "Rust"
name = "Manually vectorized"
desc = "An implementation specific to x86-64 using mostly branchless operations and operating on 32 bytes at a time."

path = "solutions/Rust/2023/d1p1_manual_simd"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d1p1_manual_simd"
clean = "cargo clean"

[[2023.01.1]]
lang = "C"
name = "Naive"
desc = "Every second of writing this was excrutiating and I never want to do it again."

path = "solutions/C/2023/d1p1_basic"

build = 'make build'
exec = "./target/d1p1"
clean = "make clean"

[[2023.01.1]]
lang = "Scala"
name = "Basic Iterator Sln"
desc = "I threw it together relatively quickly"

path = "solutions/Scala/2023/Iter"
build = "sbt package"
exec = "if type 'scala3' &> /dev/null; then SCALA=scala3; else SCALA=scala; fi; $SCALA ./target/scala-3.4.0/aocone_3-0.jar"
shell = ["sh", "-c"]
clean = "sbt clean"

[[2023.01.1]]
lang = "Scala"
name = "IteratorNative"
desc = "Basic iterator solution but native this time"

path = "solutions/Scala/2023/iternative"

build = "sbt nativeLink"
exec = "./target/scala-3.3.1/iternative-out"
clean = "sbt clean"

[[2023.01.1]]
lang = "Python"
name = "Iterators"
desc = "Iterables. It's all iterables!"

path = "solutions/Python/2023/"

exec = "python d1p1.py"

[[2023.01.2]]
lang = "Python"
name = "Iterators"
desc = "Iterables. It's all iterables!"

path = "solutions/Python/2023/"

exec = "python d1p2.py"

[[2023.04.1]]
lang = "Rust"
name = "Basic"
desc = "A somewhat simple solution using parser combinators(winnow)"

path = "solutions/Rust/2023/d4p1"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d4p1"
clean = "cargo clean"

[[2015.01.1]]
lang = "Rust"
name = "Iterator"
desc = "A one-line solution using a simple iterator"

path = "solutions/Rust/2015/d1p1"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d1p1"
clean = "cargo clean"

[[2015.01.2]]
lang = "Rust"
name = "Iterator"
desc = "A one-line solution using a simple iterator"

path = "solutions/Rust/2015/d1p2"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d1p2"
clean = "cargo clean"

[[2015.02.1]]
lang = "Rust"
name = "Iterator"
desc = "A one-line solution using a simple iterator"

path = "solutions/Rust/2015/d2p1"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d2p1"
clean = "cargo clean"

[[2015.02.2]]
lang = "Rust"
name = "Iterator"
desc = "A one-line solution using a simple iterator"

path = "solutions/Rust/2015/d2p2"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d2p2"
clean = "cargo clean"

[[2015.07.1]]
lang = "Rust"
name = "Combinators"
desc = "A solution using parser combinators(winnow)"

path = "solutions/Rust/2015/d7p1"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d7p1"
clean = "cargo clean"

[[2015.07.2]]
lang = "Rust"
name = "Combinators"
desc = "A solution using parser combinators(winnow)"

path = "solutions/Rust/2015/d7p2"

build = 'RUSTFLAGS="-C target-cpu=native" cargo build --release -q'
exec = "../../target/release/d7p2"
clean = "cargo clean"

[[2023.01.1]]
lang = "Golang"
name = "Basic Approach"
desc = "I threw this together"

path = "solutions/Go/2023/d1_basic"
build = "go build -ldflags='-s -w'"
exec = "./program"
clean = "go clean"

[[2023.01.1]]
lang = "Golang"
name = "Single pass"
desc = "Fairly basic solution to only iterate over the input once"

path = "solutions/Go/2023/d1p1_onepass"
build = "go build -ldflags='-s -w'"
exec = "./program"
clean = "go clean"

[[2023.01.1]]
lang = "Haskell"
name = "Naive and Simple"
desc = "A simple solution, without much tought put into it"

path = "solutions/Haskell/2023/d1p1/naive"
exec = "stack run"
clean = "stack clean"

[[2023.01.1]]
lang = "Haskell"
name = "Recursive"
desc = "Requires knowledge about the input format"

path = "solutions/Haskell/2023/d1p1/recursive"
exec = "stack run"
clean = "stack clean"

[[2023.01.1]]
lang = "Elixir"
name = "Lol regex approach"
desc = "Kind of bad regex solution"

path = "solutions/Elixir/2023/aoc"
build = "mix deps.get; MIX_ENV=prod mix escript.build"
exec = "./aoc d1_regex"
clean = "mix clean"

[[2023.01.1]]
lang = "Elixir"
name = "BitString approach"
desc = "Should be less horrible than the first one"

path = "solutions/Elixir/2023/aoc"
build = "mix deps.get; MIX_ENV=prod mix escript.build"
exec = "./aoc d1_no_regex"
clean = "mix clean"

[[2023.01.1]]
lang = "Elixir"
name = "Shitty Parallel"
desc = "A really lazily-made parallel implementation"

path = "solutions/Elixir/2023/aoc"
build = "mix deps.get; MIX_ENV=prod mix escript.build"
exec = "./aoc d1_no_regex_parallel"
clean = "mix clean"

[[2023.01.1]]
lang = "Elixir"
name = "Flow"
desc = "Somewhat alright parallelism featuring flow"

path = "solutions/Elixir/2023/aoc"
build = "mix deps.get; MIX_ENV=prod mix escript.build"
exec = "./aoc d1_flow"
clean = "mix clean"

[[2023.01.1]]
lang = "CSharp"
name = "Linq"
desc = "Totally lazy Linq solution"

path = "solutions/Dotnet/2023/DayOne"

build = "dotnet build -c Release"
exec = "dotnet bin/Release/net8.0/DayOne.dll"
clean = "dotnet clean"

[[2023.01.1]]
lang = "Lua"
name = "Regex"
desc = "A simple solution relying on regex"

path = "solutions/Lua/2023/d1p1"

build = "cd ../../timing_lib;make"
exec = "lua Regex.lua"

[[2023.01.1]]
lang = "LuaJIT"
name = "Regex"
desc = "A simple solution relying on regex"

path = "solutions/Lua/2023/d1p1"

build = "cd ../../timing_lib;make"
exec = "luajit Regex.lua"
